version: "3.8"

services:
  app:
    build:
      context: .
    container_name: blog-application
    ports:
      - "3000:80"
    environment:
      REACT_APP_SERVER_URL: /run/secrets/REACT_APP_SERVER_URL
      REACT_APP_BREVO_API_KEY: /run/secrets/REACT_APP_BREVO_API_KEY
      REACT_APP_BREVO_EMAIL: /run/secrets/REACT_APP_BREVO_EMAIL
      REACT_APP_BREVO_NAME: /run/secrets/REACT_APP_BREVO_NAME
      REACT_APP_FIREBASE_APIKEY: /run/secrets/REACT_APP_FIREBASE_APIKEY
      REACT_APP_FIREBASE_AUTHDOMAIN: /run/secrets/REACT_APP_FIREBASE_AUTHDOMAIN
      REACT_APP_FIREBASE_PROJECTID: /run/secrets/REACT_APP_FIREBASE_PROJECTID
      REACT_APP_FIREBASE_STORAGEBUCKET: /run/secrets/REACT_APP_FIREBASE_STORAGEBUCKET
      REACT_APP_FIREBASE_MESSAGINGSENDERID: /run/secrets/REACT_APP_FIREBASE_MESSAGINGSENDERID
      REACT_APP_FIREBASE_APPID: /run/secrets/REACT_APP_FIREBASE_APPID
      REACT_APP_FIREBASE_MEASUREMENTID: /run/secrets/REACT_APP_FIREBASE_MEASUREMENTID
    secrets:
      - REACT_APP_SERVER_URL
      - REACT_APP_BREVO_API_KEY
      - REACT_APP_BREVO_EMAIL
      - REACT_APP_BREVO_NAME
      - REACT_APP_FIREBASE_APIKEY
      - REACT_APP_FIREBASE_AUTHDOMAIN
      - REACT_APP_FIREBASE_PROJECTID
      - REACT_APP_FIREBASE_STORAGEBUCKET
      - REACT_APP_FIREBASE_MESSAGINGSENDERID
      - REACT_APP_FIREBASE_APPID
      - REACT_APP_FIREBASE_MEASUREMENTID

secrets:
  REACT_APP_SERVER_URL:
    file: ./secrets.txt
  REACT_APP_BREVO_API_KEY:
    file: ./secrets.txt
  REACT_APP_BREVO_EMAIL:
    file: ./secrets.txt
  REACT_APP_BREVO_NAME:
    file: ./secrets.txt
  REACT_APP_FIREBASE_APIKEY:
    file: ./secrets.txt
  REACT_APP_FIREBASE_AUTHDOMAIN:
    file: ./secrets.txt
  REACT_APP_FIREBASE_PROJECTID:
    file: ./secrets.txt
  REACT_APP_FIREBASE_STORAGEBUCKET:
    file: ./secrets.txt
  REACT_APP_FIREBASE_MESSAGINGSENDERID:
    file: ./secrets.txt
  REACT_APP_FIREBASE_APPID:
    file: ./secrets.txt
  REACT_APP_FIREBASE_MEASUREMENTID:
    file: ./secrets.txt