# POST http://localhost:9292/login HTTP/1.1
# content-type: application/json

# {
#     "email": "pradeep@gmail.com",
#     "password": "password"
# }

# POST http://localhost:9292/register HTTP/1.1
# content-type: application/json

# {
#     "username": "Pradeep",
#     "email": "pradeep@gmail.com",
#     "password": "password"
# }

# POST http://localhost:9292/user/post/create HTTP/1.1
# content-type: application/json

# {
#     "an_token": "d6b5ca3b9d3f3155c6bc",
#     "title": "Title 2",
#     "content": "Content in my book",
#     "category": "Art",
#     "visibility": "private"
# }

# POST http://localhost:9292/user/post/1 HTTP/1.1
# content-type: application/json

# {
#     "an_token": "d6b5ca3b9d3f3155c6bc",
#     "title": "Title 1",
#     "content": "Content in my updated book",
#     "category": "Art",
#     "visibility": "public"
# }

# #user post getting
# GET http://localhost:9292/user/post/1

# GET http://localhost:9292/post/all

# GET http://localhost:9292/post/1

# POST http://localhost:9292/post/comment/create HTTP/1/1
# content-type: application/json

# {
#     "name": "pradeep",
#     "comment": "comment"
# }

//Create Post
POST http://localhost:9292/user/posts/create HTTP/1.1
content-type: application/json

{
    "an_token": "d6b5ca3b9d3f3155c6bc",
    "title": "Title 3",
    "content": "Content in my book",
    "category": "Tech",
    "visibility": "private"
}

//Update Post
POST http://localhost:9292/user/posts/3 HTTP/1.1
content-type: application/json

{
    "an_token": "d6b5ca3b9d3f3155c6bc",
    "title": "Title 3",
    "content": "Content in my updated book",
    "category": "Tech",
    "visibility": "public"
}

//get particular post
GET http://localhost:9292/user/post/1

//get all user posts
GET http://localhost:9292/user/posts/getall

//delete particular post and should send an_token for this
# DELETE http://localhost:9292/user/post/1

//create comment for particular post
POST http://localhost:9292/post/comments/create HTTP/1/1
content-type: application/json

{
    "name": "sunil",
    "comment": "comment 2",
    "post_id": 3
}

//get all comments on post, should send post_id for this
GET http://localhost:9292/post/comments/

POST http://localhost:9292/post/comments/2 HTTP/1/1
content-type: application/json

{
    "comment": "updated comment",
}